[package]
name = "awsdsl"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = { version = "1.8.12", features = ["credentials-login"] }
aws-sdk-dynamodb = "1.101.0"
aws-sdk-s3 = "1.118.0"
aws-sdk-ec2 = { version = "1.199.0" }
tokio = { version = "1.48.0", features = ["full"] }
